{{- if .Values.observability.opensearch.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: opensearch-config
  namespace: {{ .Release.Namespace }}
data:
  opensearch.yml: |
    cluster.name: failure-puzzle
    node.name: opensearch-node-1
    discovery.type: single-node
    http.port: 9200
    plugins.security.disabled: true
    bootstrap.memory_lock: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
  namespace: {{ .Release.Namespace }}
  labels:
    app: opensearch
spec:
  replicas: {{ .Values.observability.opensearch.replicas }}
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:1.35
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: opensearch
        image: opensearchproject/opensearch:2.11.0
        env:
        - name: discovery.type
          value: single-node
        - name: plugins.security.disabled
          value: "true"
        - name: OPENSEARCH_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        resources:
          {{- toYaml .Values.observability.opensearch.resources | nindent 10 }}
        volumeMounts:
        - name: opensearch-data
          mountPath: /usr/share/opensearch/data
        - name: opensearch-config
          mountPath: /usr/share/opensearch/config/opensearch.yml
          subPath: opensearch.yml
      volumes:
      - name: opensearch-data
        emptyDir: {}
      - name: opensearch-config
        configMap:
          name: opensearch-config
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: {{ .Release.Namespace }}
  labels:
    app: opensearch
spec:
  type: ClusterIP
  ports:
  - port: 9200
    targetPort: 9200
    name: http
  selector:
    app: opensearch
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch-external
  namespace: {{ .Release.Namespace }}
  labels:
    app: opensearch
spec:
  type: LoadBalancer
  ports:
  - port: 9200
    targetPort: 9200
    name: http
  selector:
    app: opensearch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch-dashboards
  namespace: {{ .Release.Namespace }}
  labels:
    app: opensearch-dashboards
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch-dashboards
  template:
    metadata:
      labels:
        app: opensearch-dashboards
    spec:
      containers:
      - name: opensearch-dashboards
        image: opensearchproject/opensearch-dashboards:2.11.0
        env:
        - name: OPENSEARCH_HOSTS
          value: '["http://opensearch:9200"]'
        - name: DISABLE_SECURITY_DASHBOARDS_PLUGIN
          value: "true"
        ports:
        - containerPort: 5601
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch-dashboards
  namespace: {{ .Release.Namespace }}
  labels:
    app: opensearch-dashboards
spec:
  type: LoadBalancer
  ports:
  - port: 5601
    targetPort: 5601
    name: http
  selector:
    app: opensearch-dashboards
{{- end }}
